name: Keep-alive

on:
  schedule:
    - cron: '0 0 */30 * *' # every 30 days
  workflow_dispatch:       # Allow manual trigger

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Keep alive log
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Workflow active on $(date)" >> activity.log
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git add activity.log
          git commit -m "Keep repo active [skip ci]" || echo "No changes to commit"
          git push
