name: Keep-alive

on:
  schedule:
    - cron: '0 0 */30 * *' # every 30 days
  workflow_dispatch:       # Allow manual trigger


jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow active on $(date)"
